[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/bengentil/rindexer:cross-armv7-unknown-linux-musleabihf-0.2.1-sqlite"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/bengentil/rindexer:cross-x86_64-unknown-linux-musl-0.2.1-sqlite"
